---
changelog:
  categories:
    - title: Breaking Changes
      labels: [breaking-change]
    - title: New Features
      labels: [enhancement]
    - title: Improvements to the Documentation
      labels: [documentation]
    - title: Other Changes
      labels: ['*']
